<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.SVG" Version="26.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="chatot_front\src\app\common\" />
    <Folder Include="chatot_front\src\app\multi\" />
    <Folder Include="chatot_front\src\app\solo\" />
  </ItemGroup>

</Project>
